import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import "../globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ArticleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="light" lang="en">
      <Head>
        <title>La perdiz critica</title>
        <meta property="og:title" content="La perdiz critica" key="title" />
      </Head>
      <body className={inter.className}>
        <main className="grid max-w-[1280px] px-4 h-[1280px] gap-x-4 mx-auto text-base grid-custom">
          <div className="article-header col-start-1 col-end-3 flex items-center h-[56px]">
            <span className="mr-4 block">
              <a className="max-w-[200px] align-middle inline-flex items-center">
                <Image
                  alt="logo image"
                  src="/lpc.jpg"
                  width="50"
                  height="40"
                  className="align-middle inline-block object-contain"
                />
              </a>
            </span>
            <div className="flex flex-1 items-center">
              <span className="inline-block mr-2 whitespace-nowrap">
                Create Post
              </span>
            </div>
            <nav className="ml-auto flex">
              <ul className="list-none p-0 m-0 flex w-full">
                <li className="list-item w-full m-0">Edit</li>
                <li className="list-item w-full m-0">Preview</li>
              </ul>
            </nav>
            <div className="close absolute right-2 top-2 ml-0">
              <button>
                <svg
                  aria-hidden="true"
                  focusable="false"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  xmlns="http://www.w3.org/2000/svg"
                  className="crayons-icon c-btn__icon"
                >
                  <path d="m12 10.586 4.95-4.95 1.414 1.414-4.95 4.95 4.95 4.95-1.414 1.414-4.95-4.95-4.95 4.95-1.414-1.414 4.95-4.95-4.95-4.95L7.05 5.636l4.95 4.95z"></path>
                </svg>
              </button>
            </div>
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
